// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hndmscdfnvrztvruuvyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZG1zY2RmbnZyenR2cnV1dnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzU4ODMsImV4cCI6MjA2MzMxMTg4M30.MFSEIDHClzXbY5lnVLI7aSD6UjA6tUUWdaE3slsr6pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
